name: "OpenAPI Change Checker"
description: "Track and report OpenAPI specification changes"
author: "OpenAPI Change Checker"

inputs:
  spec_source:
    description: 'Source of OpenAPI spec (fastapi or static)'
    required: true
  fastapi_app:
    description: 'Path to FastAPI app (required if spec_source is fastapi)'
    required: false
  openapi_file:
    description: 'Path to static OpenAPI spec file (required if spec_source is static)'
    required: false
  consumers_config:
    description: 'Path to consumers configuration file'
    required: false

runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/openapi-check.yml