name: "OpenAPI Change Checker"
description: "Track and report OpenAPI specification changes"
author: "OpenAPI Change Checker"

inputs:
  spec_source:
    description: 'Source of OpenAPI spec (fastapi or static)'
    required: true
  fastapi_app:
    description: 'Path to FastAPI app (required if spec_source is fastapi)'
    required: false
  openapi_file:
    description: 'Path to static OpenAPI spec file (required if spec_source is static)'
    required: false
  consumers_config:
    description: 'Path to consumers configuration file'
    required: false
  token:
    description: 'A Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.11'
    - name: checkout action code
      uses: actions/checkout@v4
      with:
          repository: willsfidell/openapi_change_checker
          path: ${{ github.workspace }}/occ
    - name: Install and build
      shell: bash
      run: |
        pip install ${{ github.workspace }}/occ
    - name: Check OpenAPI changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        python -m openapi_change_checker check \
          --spec-source ${{ inputs.spec_source || 'static' }} \
          --fastapi-app ${{ inputs.fastapi_app || '' }} \
          --openapi-file ${{ inputs.openapi_file || 'openapi.json' }} \
          --consumers-config ${{ inputs.consumers_config || '' }} \
          --repo ${{ github.repository }} \
          --pr ${{ github.event.pull_request.number }}