name: OpenAPI Change Checker

on:
  workflow_call:
    inputs:
      spec_source:
        description: 'Source of OpenAPI spec (fastapi or static)'
        required: true
        type: string
      fastapi_app:
        description: 'Path to FastAPI app (required if spec_source is fastapi)'
        required: false
        type: string
      openapi_file:
        description: 'Path to static OpenAPI spec file (required if spec_source is static)'
        required: false
        type: string
      consumers_config:
        description: 'Path to consumers configuration file'
        required: false
        type: string
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'  # For FastAPI apps
      - '**/openapi.json'  # For static specs
  push:
    branches: [ main ]
    paths:
      - '**.py'  # For FastAPI apps
      - '**/openapi.json'  # For static specs

permissions:
  contents: read
  pull-requests: write

jobs:
  check-openapi-changes:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for base branch comparison

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Check OpenAPI changes
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m openapi_change_checker check \
          --spec-source ${{ inputs.spec_source || 'static' }} \
          --fastapi-app ${{ inputs.fastapi_app || '' }} \
          --openapi-file ${{ inputs.openapi_file || 'openapi.json' }} \
          --consumers-config ${{ inputs.consumers_config || '' }} \
          --repo ${{ github.repository }} \
          --pr ${{ github.event.pull_request.number }}

    - name: Store OpenAPI spec
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: .artifacts/openapi.json
        retention-days: 90